parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\StatisticsService:
        arguments:
            $dataFile: '%kernel.project_dir%/data/stats.json'
